version: '3'

services:

  balhom-api:
    image: fabbo/balhom-api:drf
    container_name: balhom-api
    env_file:
      - ./api.env
    #volumes:
      #- balhom-api-certs:/certs:ro  # Uncomment for HTTPS
    ports:
      - "8000:80"
      #- "443:443"  # Uncomment for HTTPS
    depends_on:
      - balhom-celery-worker
      - balhom-celery-beat
    restart: unless-stopped
    networks:
      - balhom-api-net

  balhom-celery-worker:
    image: fabbo/balhom-api:drf
    container_name: balhom-celery-worker
    env_file:
      - ./api.env
    restart: unless-stopped
    entrypoint: /app/celery_worker_entrypoint.sh
    networks:
      - balhom-api-net

  balhom-celery-beat:
    image: fabbo/balhom-api:drf
    container_name: balhom-celery-beat
    env_file:
      - ./api.env
    restart: unless-stopped
    entrypoint: /app/celery_beat_entrypoint.sh
    networks:
      - balhom-api-net

networks:
  balhom-api-net:
