version: '3'

services:

  balhom-api-djangorest:
    image: fabbo/balhom-api-djangorest:latest
    container_name: balhom-api-djangorest
    env_file:
      - ./api.env
    #volumes:
      #- balhom-api-djangorest-certs:/certs:ro  # Uncomment for HTTPS
    ports:
      - "8000:80"
      #- "443:443"  # Uncomment for HTTPS
    depends_on:
      - balhom-celery-worker
      - balhom-celery-beat
    restart: unless-stopped
    networks:
      - balhom-api-net

  balhom-celery-worker:
    image: fabbo/balhom-api-djangorest:latest
    container_name: balhom-celery-worker
    env_file:
      - ./api.env
    restart: unless-stopped
    entrypoint: /app/celery_worker_entrypoint.sh
    networks:
      - balhom-api-net

  balhom-celery-beat:
    image: fabbo/balhom-api-djangorest:latest
    container_name: balhom-celery-beat
    env_file:
      - ./api.env
    restart: unless-stopped
    entrypoint: /app/celery_beat_entrypoint.sh
    networks:
      - balhom-api-net

volumes:
  balhom-api-djangorest-logs:
  balhom-celery-beat-logs:
  balhom-celery-worker-logs:

networks:
  balhom-api-net:
