# Generated by Django 4.2.8 on 2023-12-21 07:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('type', models.CharField(choices=[('REVENUE', 'revenue'), ('EXPENSE', 'expense')], max_length=10)),
                ('image', models.ImageField(default='core/default_image.jpg', upload_to='balance/type', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Balance type',
                'verbose_name_plural': 'Balance types',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_quantity', models.FloatField(default=0, verbose_name='gross quantity')),
                ('expected_quantity', models.FloatField(default=0, verbose_name='expected quantity')),
                ('currency_type', models.CharField(max_length=4, verbose_name='currency type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='year')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Monthly balance',
                'verbose_name_plural': 'Monthly balances',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('description', models.CharField(blank=True, default='', max_length=2000, verbose_name='description')),
                ('real_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='real quantity')),
                ('converted_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='converted quantity')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('currency_type', models.CharField(max_length=4, verbose_name='currency type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('balance_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='balance.balancetype', verbose_name='balance type')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnnualBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_quantity', models.FloatField(default=0, verbose_name='gross quantity')),
                ('expected_quantity', models.FloatField(default=0, verbose_name='expected quantity')),
                ('currency_type', models.CharField(max_length=4, verbose_name='currency type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='year')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Annual balance',
                'verbose_name_plural': 'Annual balances',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
