# Generated by Django 4.2.5 on 2023-10-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balancetype',
            unique_together=set(),
        ),
    ]
