# Generated by Django 4.2.5 on 2023-10-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancetype',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Balance type', 'verbose_name_plural': 'Balance types'},
        ),
    ]
