apiVersion: v1
kind: Service
metadata:
  name: balhom-api-service
  namespace: balhom
  labels:
    app: balhom-api
spec:
  selector:
    app: balhom-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
