apiVersion: v1
kind: Service
metadata:
  name: balhom-celery-flower-service
  namespace: default
  labels:
    app: balhom-celery-flower
spec:
  selector:
    app: balhom-celery-flower
  type: NodePort
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
      nodePort: 30555
