name: Django Rest App Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build-test-upload:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install
        working-directory: ./api/src

      - name: Run tests
        run: |
          poetry run python manage.py test
        working-directory: ./api/src
      
      - name: Check deploy
        run: |
          poetry run python manage.py check --deploy
        working-directory: ./api/src
      
      - name: Check migrations
        run: |
          poetry run python manage.py makemigrations
        working-directory: ./api/src
        
      - name: Check build Docker Image
        run: |
          IMAGE_TAG="${DOCKER_REPO_NAME}:drf"
          docker build . -t ${IMAGE_TAG}
        env:
          DOCKER_REPO_NAME: ${{ secrets.DOCKER_REPO_NAME }}
        working-directory: ./api
