name: Django Rest App Build, Test, Upload to Docker Hub and Create Tag

on:
  push:
    branches:
      - main

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install
        working-directory: ./api/src

      - name: Run tests
        run: |
          poetry run python manage.py test
        working-directory: ./api/src
      
      - name: Check deploy
        run: |
          poetry run python manage.py check --deploy
        working-directory: ./api/src
      
      - name: Make migrations
        run: |
          poetry run python manage.py makemigrations
        working-directory: ./api/src

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          export APP_VERSION=$(grep -m 1 version src/pyproject.toml | tr -d '=' | cut -d' ' -f3 | tr -d '"' | tr -d '\n' | tr -d '\r')
          echo "Using version ${APP_VERSION}"
          # Tag variables
          IMAGE_TAG="${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:${APP_VERSION}"
          DRF_TAG="${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:drf"
          LATEST_TAG="${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:latest"
          # Image build
          docker build . -t ${IMAGE_TAG}
          # Image tag
          docker tag ${IMAGE_TAG} "${IMAGE_TAG}-drf"
          docker tag ${IMAGE_TAG} ${DRF_TAG}
          docker tag ${IMAGE_TAG} ${LATEST_TAG}
          # Image push
          docker push ${IMAGE_TAG}
          docker push "${IMAGE_TAG}-drf"
          docker push ${DRF_TAG}
          docker push ${LATEST_TAG}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_REPO_NAME: ${{ secrets.DOCKER_REPO_NAME }}
        working-directory: ./api
